# Site
name: "ArtCraft Games"
title: "ArtCraft Games"
description: "Game engine"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: '/blog'
google_analytics: 'UA-xxxxxxxx-1'
disqus:
mailchimp-list: 
include: ["_pages"]
permalink: /:title/
email: georgii@artcraft.games

# Authors
authors:
  georgii:
    name: Georgii Kharlampiiev
    display_name: Georgii
    avatar: 'assets/images/avatar-georgii.png'
    email: georgii@artcraft.games
    web: https://artcraft.games/
    twitter: https://x.com/kharlampiiev
    description: "Develop with love"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
